### PR TITLE
Update plugin.webpconverter.php

### PR DESCRIPTION
**Pull request by Bahbv**
Added an extra check to see if the webp isn't a damaged file. 

This occured to me when it gave an error while converting a PNG file. 
The .webp was made but was corrupted with a size of 0kb.

### CODE REVIEW

**Comment by fourroses666** [comment]
Noticed the same issue! After re-saving the .png with PS it worked again.

**Comment by Bahbv** [comment]
Yeah, i think it has to do with the colors of the image. They should be in RGB.
EVO gave the following error: Paletter image not supported by webp.

**Comment by mplavala** [comment]
@Bahbv could you please share the image? Maybe I can fix the plugin so that the image is converted properly. Thanks

**Comment by Bahbv** [comment]
Yes but i would rather do that by email. You can send me one to: bob [at] bahbv . net  
Maybe you could use [imagepalettetotruecolor()](https://www.php.net/manual/en/function.imagepalettetotruecolor.php).

**Pull request merged**
